using System;
using System.Collections.Generic;
using System.Text;

namespace Brass {
    public partial class Program {
        public static void GenerateDefaultTable() {
            AllInstructions.Add(new Instruction("adc", "a,(hl)", 1, new byte[] { 0x8E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,(ix*)", 3, new byte[] { 0xDD, 0x8E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,(iy*)", 3, new byte[] { 0xFD, 0x8E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,a", 1, new byte[] { 0x8F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,b", 1, new byte[] { 0x88 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,c", 1, new byte[] { 0x89 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,d", 1, new byte[] { 0x8A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,e", 1, new byte[] { 0x8B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,h", 1, new byte[] { 0x8C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,l", 1, new byte[] { 0x8D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,ixh", 2, new byte[] { 0xDD, 0x8C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,ixl", 2, new byte[] { 0xDD, 0x8D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,iyh", 2, new byte[] { 0xFD, 0x8C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,iyl", 2, new byte[] { 0xFD, 0x8D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "a,*", 2, new byte[] { 0xCE }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "hl,bc", 2, new byte[] { 0xED, 0x4A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "hl,de", 2, new byte[] { 0xED, 0x5A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "hl,hl", 2, new byte[] { 0xED, 0x6A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("adc", "hl,sp", 2, new byte[] { 0xED, 0x7A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,(hl)", 1, new byte[] { 0x86 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,(ix*)", 3, new byte[] { 0xDD, 0x86 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,(iy*)", 3, new byte[] { 0xFD, 0x86 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,a", 1, new byte[] { 0x87 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,b", 1, new byte[] { 0x80 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,c", 1, new byte[] { 0x81 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,d", 1, new byte[] { 0x82 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,e", 1, new byte[] { 0x83 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,h", 1, new byte[] { 0x84 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,l", 1, new byte[] { 0x85 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,ixh", 2, new byte[] { 0xDD, 0x84 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,ixl", 2, new byte[] { 0xDD, 0x85 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,iyh", 2, new byte[] { 0xFD, 0x84 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,iyl", 2, new byte[] { 0xFD, 0x85 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "a,*", 2, new byte[] { 0xC6 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "hl,bc", 1, new byte[] { 0x09 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "hl,de", 1, new byte[] { 0x19 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "hl,hl", 1, new byte[] { 0x29 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "hl,sp", 1, new byte[] { 0x39 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "ix,bc", 2, new byte[] { 0xDD, 0x09 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "ix,de", 2, new byte[] { 0xDD, 0x19 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "ix,ix", 2, new byte[] { 0xDD, 0x29 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "ix,sp", 2, new byte[] { 0xDD, 0x39 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "iy,bc", 2, new byte[] { 0xFD, 0x09 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "iy,de", 2, new byte[] { 0xFD, 0x19 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "iy,iy", 2, new byte[] { 0xFD, 0x29 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("add", "iy,sp", 2, new byte[] { 0xFD, 0x39 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "(hl)", 1, new byte[] { 0xA6 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "(ix*)", 3, new byte[] { 0xDD, 0xA6 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "(iy*)", 3, new byte[] { 0xFD, 0xA6 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "a", 1, new byte[] { 0xA7 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "b", 1, new byte[] { 0xA0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "c", 1, new byte[] { 0xA1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "d", 1, new byte[] { 0xA2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "e", 1, new byte[] { 0xA3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "h", 1, new byte[] { 0xA4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "l", 1, new byte[] { 0xA5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "ixh", 2, new byte[] { 0xDD, 0xA4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "ixl", 2, new byte[] { 0xDD, 0xA4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "iyh", 2, new byte[] { 0xFD, 0xA4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "iyl", 2, new byte[] { 0xFD, 0xA4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("and", "*", 2, new byte[] { 0xE6 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,(hl)", 2, new byte[] { 0xCB, 0x46 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZBit, 1, 0, 0x4600));
            AllInstructions.Add(new Instruction("bit", "*,(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZBit, 1, 0, 0x4600));
            AllInstructions.Add(new Instruction("bit", "*,a", 2, new byte[] { 0xCB, 0x47 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,b", 2, new byte[] { 0xCB, 0x40 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,c", 2, new byte[] { 0xCB, 0x41 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,d", 2, new byte[] { 0xCB, 0x42 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,e", 2, new byte[] { 0xCB, 0x43 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,h", 2, new byte[] { 0xCB, 0x44 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("bit", "*,l", 2, new byte[] { 0xCB, 0x45 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "c,*", 3, new byte[] { 0xDC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "m,*", 3, new byte[] { 0xFC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "nc,*", 3, new byte[] { 0xD4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "nz,*", 3, new byte[] { 0xC4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "p,*", 3, new byte[] { 0xF4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "pe,*", 3, new byte[] { 0xEC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "po,*", 3, new byte[] { 0xE4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "z,*", 3, new byte[] { 0xCC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("call", "*", 3, new byte[] { 0xCD }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ccf", "\"\"", 1, new byte[] { 0x3F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "(hl)", 1, new byte[] { 0xBE }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "(ix*)", 3, new byte[] { 0xDD, 0xBE }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "(iy*)", 3, new byte[] { 0xFD, 0xBE }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "a", 1, new byte[] { 0xBF }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "b", 1, new byte[] { 0xB8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "c", 1, new byte[] { 0xB9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "d", 1, new byte[] { 0xBA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "e", 1, new byte[] { 0xBB }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "h", 1, new byte[] { 0xBC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "l", 1, new byte[] { 0xBD }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "ixh", 2, new byte[] { 0xDD, 0xBC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "ixl", 2, new byte[] { 0xDD, 0xBD }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "iyh", 2, new byte[] { 0xFD, 0xBC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "iyl", 2, new byte[] { 0xFD, 0xBD }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cp", "*", 2, new byte[] { 0xFE }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cpd", "\"\"", 2, new byte[] { 0xED, 0xA9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cpdr", "\"\"", 2, new byte[] { 0xED, 0xB9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cpir", "\"\"", 2, new byte[] { 0xED, 0xB1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cpi", "\"\"", 2, new byte[] { 0xED, 0xA1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("cpl", "\"\"", 1, new byte[] { 0x2F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("daa", "\"\"", 1, new byte[] { 0x27 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "(hl)", 1, new byte[] { 0x35 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "(ix*)", 3, new byte[] { 0xDD, 0x35 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "(iy*)", 3, new byte[] { 0xFD, 0x35 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "a", 1, new byte[] { 0x3D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "b", 1, new byte[] { 0x05 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "bc", 1, new byte[] { 0x0B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "c", 1, new byte[] { 0x0D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "d", 1, new byte[] { 0x15 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "de", 1, new byte[] { 0x1B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "e", 1, new byte[] { 0x1D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "h", 1, new byte[] { 0x25 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "hl", 1, new byte[] { 0x2B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "ix", 2, new byte[] { 0xDD, 0x2B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "iy", 2, new byte[] { 0xFD, 0x2B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "l", 1, new byte[] { 0x2D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "sp", 1, new byte[] { 0x3B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("di", "\"\"", 1, new byte[] { 0xF3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("djnz", "*", 2, new byte[] { 0x10 }, Instruction.InstructionRule.R1, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ei", "\"\"", 1, new byte[] { 0xFB }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ex", "(sp),hl", 1, new byte[] { 0xE3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ex", "(sp),ix", 2, new byte[] { 0xDD, 0xE3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ex", "(sp),iy", 2, new byte[] { 0xFD, 0xE3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ex", "af,af'", 1, new byte[] { 0x08 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ex", "de,hl", 1, new byte[] { 0xEB }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("exx", "\"\"", 1, new byte[] { 0xD9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("halt", "\"\"", 1, new byte[] { 0x76 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("im", "0", 2, new byte[] { 0xED, 0x46 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("im", "1", 2, new byte[] { 0xED, 0x56 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("im", "2", 2, new byte[] { 0xED, 0x5E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "(c)", 2, new byte[] { 0xED, 0x70 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "f,(c)", 2, new byte[] { 0xED, 0x70 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "a,(c)", 2, new byte[] { 0xED, 0x78 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "b,(c)", 2, new byte[] { 0xED, 0x40 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "c,(c)", 2, new byte[] { 0xED, 0x48 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "d,(c)", 2, new byte[] { 0xED, 0x50 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "e,(c)", 2, new byte[] { 0xED, 0x58 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "h,(c)", 2, new byte[] { 0xED, 0x60 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "l,(c)", 2, new byte[] { 0xED, 0x68 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in", "a,(*)", 2, new byte[] { 0xDB }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("in0", "a,(*)", 3, new byte[] { 0xED, 0x38 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in0", "b,(*)", 3, new byte[] { 0xED, 0x00 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in0", "c,(*)", 3, new byte[] { 0xED, 0x08 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in0", "d,(*)", 3, new byte[] { 0xED, 0x10 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in0", "e,(*)", 3, new byte[] { 0xED, 0x18 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in0", "h,(*)", 3, new byte[] { 0xED, 0x20 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("in0", "l,(*)", 3, new byte[] { 0xED, 0x28 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "(hl)", 1, new byte[] { 0x34 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "(ix*)", 3, new byte[] { 0xDD, 0x34 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "(iy*)", 3, new byte[] { 0xFD, 0x34 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "a", 1, new byte[] { 0x3C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "b", 1, new byte[] { 0x04 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "bc", 1, new byte[] { 0x03 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "c", 1, new byte[] { 0x0C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "d", 1, new byte[] { 0x14 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "de", 1, new byte[] { 0x13 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "e", 1, new byte[] { 0x1C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "h", 1, new byte[] { 0x24 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "hl", 1, new byte[] { 0x23 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "ix", 2, new byte[] { 0xDD, 0x23 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "iy", 2, new byte[] { 0xFD, 0x23 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "l", 1, new byte[] { 0x2C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "sp", 1, new byte[] { 0x33 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ind", "\"\"", 2, new byte[] { 0xED, 0xAA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("indr", "\"\"", 2, new byte[] { 0xED, 0xBA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ini", "\"\"", 2, new byte[] { 0xED, 0xA2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inir", "\"\"", 2, new byte[] { 0xED, 0xB2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "(hl)", 1, new byte[] { 0xE9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "(ix)", 2, new byte[] { 0xDD, 0xE9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "(iy)", 2, new byte[] { 0xFD, 0xE9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "c,*", 3, new byte[] { 0xDA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "m,*", 3, new byte[] { 0xFA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "nc,*", 3, new byte[] { 0xD2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "nz,*", 3, new byte[] { 0xC2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "p,*", 3, new byte[] { 0xF2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "pe,*", 3, new byte[] { 0xEA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "po,*", 3, new byte[] { 0xE2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "z,*", 3, new byte[] { 0xCA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jp", "*", 3, new byte[] { 0xC3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jr", "c,*", 2, new byte[] { 0x38 }, Instruction.InstructionRule.R1, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jr", "nc,*", 2, new byte[] { 0x30 }, Instruction.InstructionRule.R1, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jr", "nz,*", 2, new byte[] { 0x20 }, Instruction.InstructionRule.R1, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jr", "z,*", 2, new byte[] { 0x28 }, Instruction.InstructionRule.R1, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("jr", "*", 2, new byte[] { 0x18 }, Instruction.InstructionRule.R1, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(bc),a", 1, new byte[] { 0x02 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(de),a", 1, new byte[] { 0x12 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),a", 1, new byte[] { 0x77 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),b", 1, new byte[] { 0x70 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),c", 1, new byte[] { 0x71 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),d", 1, new byte[] { 0x72 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),e", 1, new byte[] { 0x73 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),h", 1, new byte[] { 0x74 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),l", 1, new byte[] { 0x75 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(hl),*", 2, new byte[] { 0x36 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),a", 3, new byte[] { 0xDD, 0x77 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),b", 3, new byte[] { 0xDD, 0x70 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),c", 3, new byte[] { 0xDD, 0x71 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),d", 3, new byte[] { 0xDD, 0x72 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),e", 3, new byte[] { 0xDD, 0x73 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),h", 3, new byte[] { 0xDD, 0x74 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),l", 3, new byte[] { 0xDD, 0x75 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(ix*),*", 4, new byte[] { 0xDD, 0x36 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),a", 3, new byte[] { 0xFD, 0x77 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),b", 3, new byte[] { 0xFD, 0x70 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),c", 3, new byte[] { 0xFD, 0x71 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),d", 3, new byte[] { 0xFD, 0x72 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),e", 3, new byte[] { 0xFD, 0x73 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),h", 3, new byte[] { 0xFD, 0x74 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),l", 3, new byte[] { 0xFD, 0x75 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(iy*),*", 4, new byte[] { 0xFD, 0x36 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(*),a", 3, new byte[] { 0x32 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(*),bc", 4, new byte[] { 0xED, 0x43 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(*),de", 4, new byte[] { 0xED, 0x53 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(*),hl", 3, new byte[] { 0x22 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(*),ix", 4, new byte[] { 0xDD, 0x22 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(*),iy", 4, new byte[] { 0xFD, 0x22 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "(*),sp", 4, new byte[] { 0xED, 0x73 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,(bc)", 1, new byte[] { 0x0A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,(de)", 1, new byte[] { 0x1A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,(hl)", 1, new byte[] { 0x7E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,(ix*)", 3, new byte[] { 0xDD, 0x7E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,(iy*)", 3, new byte[] { 0xFD, 0x7E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,a", 1, new byte[] { 0x7F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,b", 1, new byte[] { 0x78 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,c", 1, new byte[] { 0x79 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,d", 1, new byte[] { 0x7A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,e", 1, new byte[] { 0x7B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,h", 1, new byte[] { 0x7C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,i", 2, new byte[] { 0xED, 0x57 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,l", 1, new byte[] { 0x7D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,r", 2, new byte[] { 0xED, 0x5F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,ixh", 2, new byte[] { 0xDD, 0x7C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,ixl", 2, new byte[] { 0xDD, 0x7D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,iyh", 2, new byte[] { 0xFD, 0x7C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,iyl", 2, new byte[] { 0xFD, 0x7D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,(*)", 3, new byte[] { 0x3A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "a,*", 2, new byte[] { 0x3E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,(hl)", 1, new byte[] { 0x46 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,(ix*)", 3, new byte[] { 0xDD, 0x46 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,(iy*)", 3, new byte[] { 0xFD, 0x46 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,a", 1, new byte[] { 0x47 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,b", 1, new byte[] { 0x40 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,c", 1, new byte[] { 0x41 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,d", 1, new byte[] { 0x42 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,e", 1, new byte[] { 0x43 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,h", 1, new byte[] { 0x44 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,l", 1, new byte[] { 0x45 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,ixh", 2, new byte[] { 0xDD, 0x44 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,ixl", 2, new byte[] { 0xDD, 0x45 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,iyh", 2, new byte[] { 0xFD, 0x44 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,iyl", 2, new byte[] { 0xFD, 0x45 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "b,*", 2, new byte[] { 0x06 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "bc,(*)", 4, new byte[] { 0xED, 0x4B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "bc,*", 3, new byte[] { 0x01 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,(hl)", 1, new byte[] { 0x4E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,(ix*)", 3, new byte[] { 0xDD, 0x4E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,(iy*)", 3, new byte[] { 0xFD, 0x4E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,a", 1, new byte[] { 0x4F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,b", 1, new byte[] { 0x48 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,c", 1, new byte[] { 0x49 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,d", 1, new byte[] { 0x4A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,e", 1, new byte[] { 0x4B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,h", 1, new byte[] { 0x4C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,l", 1, new byte[] { 0x4D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,ixh", 2, new byte[] { 0xDD, 0x4C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,ixl", 2, new byte[] { 0xDD, 0x4D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,iyh", 2, new byte[] { 0xFD, 0x4C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,iyl", 2, new byte[] { 0xFD, 0x4D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "c,*", 2, new byte[] { 0x0E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,(hl)", 1, new byte[] { 0x56 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,(ix*)", 3, new byte[] { 0xDD, 0x56 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,(iy*)", 3, new byte[] { 0xFD, 0x56 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,a", 1, new byte[] { 0x57 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,b", 1, new byte[] { 0x50 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,c", 1, new byte[] { 0x51 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,d", 1, new byte[] { 0x52 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,e", 1, new byte[] { 0x53 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,h", 1, new byte[] { 0x54 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,l", 1, new byte[] { 0x55 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,ixh", 2, new byte[] { 0xDD, 0x54 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,ixl", 2, new byte[] { 0xDD, 0x55 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,iyh", 2, new byte[] { 0xFD, 0x54 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,iyl", 2, new byte[] { 0xFD, 0x55 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "d,*", 2, new byte[] { 0x16 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "de,(*)", 4, new byte[] { 0xED, 0x5B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "de,*", 3, new byte[] { 0x11 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,(hl)", 1, new byte[] { 0x5E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,(ix*)", 3, new byte[] { 0xDD, 0x5E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,(iy*)", 3, new byte[] { 0xFD, 0x5E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,a", 1, new byte[] { 0x5F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,b", 1, new byte[] { 0x58 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,c", 1, new byte[] { 0x59 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,d", 1, new byte[] { 0x5A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,e", 1, new byte[] { 0x5B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,h", 1, new byte[] { 0x5C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,l", 1, new byte[] { 0x5D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,ixh", 2, new byte[] { 0xDD, 0x5C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,ixl", 2, new byte[] { 0xDD, 0x5D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,iyh", 2, new byte[] { 0xFD, 0x5C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,iyl", 2, new byte[] { 0xFD, 0x5D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "e,*", 2, new byte[] { 0x1E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,(hl)", 1, new byte[] { 0x66 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,(ix*)", 3, new byte[] { 0xDD, 0x66 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,(iy*)", 3, new byte[] { 0xFD, 0x66 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,a", 1, new byte[] { 0x67 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,b", 1, new byte[] { 0x60 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,c", 1, new byte[] { 0x61 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,d", 1, new byte[] { 0x62 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,e", 1, new byte[] { 0x63 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,h", 1, new byte[] { 0x64 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,l", 1, new byte[] { 0x65 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "h,*", 2, new byte[] { 0x26 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "hl,(*)", 3, new byte[] { 0x2A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "hl,*", 3, new byte[] { 0x21 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "i,a", 2, new byte[] { 0xED, 0x47 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ix,(*)", 4, new byte[] { 0xDD, 0x2A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ix,*", 4, new byte[] { 0xDD, 0x21 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iy,(*)", 4, new byte[] { 0xFD, 0x2A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iy,*", 4, new byte[] { 0xFD, 0x21 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,(hl)", 1, new byte[] { 0x6E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,(ix*)", 3, new byte[] { 0xDD, 0x6E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,(iy*)", 3, new byte[] { 0xFD, 0x6E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,a", 1, new byte[] { 0x6F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,b", 1, new byte[] { 0x68 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,c", 1, new byte[] { 0x69 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,d", 1, new byte[] { 0x6A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,e", 1, new byte[] { 0x6B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,h", 1, new byte[] { 0x6C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,l", 1, new byte[] { 0x6D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "l,*", 2, new byte[] { 0x2E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "r,a", 2, new byte[] { 0xED, 0x4F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "sp,(*)", 4, new byte[] { 0xED, 0x7B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "sp,hl", 1, new byte[] { 0xF9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "sp,ix", 2, new byte[] { 0xDD, 0xF9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "sp,iy", 2, new byte[] { 0xFD, 0xF9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "sp,*", 3, new byte[] { 0x31 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ldd", "\"\"", 2, new byte[] { 0xED, 0xA8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("lddr", "\"\"", 2, new byte[] { 0xED, 0xB8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ldi", "\"\"", 2, new byte[] { 0xED, 0xA0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ldir", "\"\"", 2, new byte[] { 0xED, 0xB0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("neg", "\"\"", 2, new byte[] { 0xED, 0x44 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("nop", "\"\"", 1, new byte[] { 0x00 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("mlt", "bc", 2, new byte[] { 0xED, 0x4C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("mlt", "de", 2, new byte[] { 0xED, 0x5C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("mlt", "hl", 2, new byte[] { 0xED, 0x6C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("mlt", "sp", 2, new byte[] { 0xED, 0x7C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "(hl)", 1, new byte[] { 0xB6 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "(ix*)", 3, new byte[] { 0xDD, 0xB6 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "(iy*)", 3, new byte[] { 0xFD, 0xB6 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "a", 1, new byte[] { 0xB7 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "b", 1, new byte[] { 0xB0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "c", 1, new byte[] { 0xB1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "d", 1, new byte[] { 0xB2 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "e", 1, new byte[] { 0xB3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "h", 1, new byte[] { 0xB4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "l", 1, new byte[] { 0xB5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "ixh", 2, new byte[] { 0xDD, 0xB4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "ixl", 2, new byte[] { 0xDD, 0xB4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "iyh", 2, new byte[] { 0xFD, 0xB4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "iyl", 2, new byte[] { 0xFD, 0xB4 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("or", "*", 2, new byte[] { 0xF6 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("otdm", "\"\"", 2, new byte[] { 0xED, 0x8B }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("otdmr", "\"\"", 2, new byte[] { 0xED, 0x9B }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("otdr", "\"\"", 2, new byte[] { 0xED, 0xBB }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("otim", "\"\"", 2, new byte[] { 0xED, 0x83 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("otimr", "\"\"", 2, new byte[] { 0xED, 0x93 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("otir", "\"\"", 2, new byte[] { 0xED, 0xB3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),a", 2, new byte[] { 0xED, 0x79 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),b", 2, new byte[] { 0xED, 0x41 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),c", 2, new byte[] { 0xED, 0x49 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),d", 2, new byte[] { 0xED, 0x51 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),e", 2, new byte[] { 0xED, 0x59 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),h", 2, new byte[] { 0xED, 0x61 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),l", 2, new byte[] { 0xED, 0x69 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(*),a", 2, new byte[] { 0xD3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("out", "(c),0", 2, new byte[] { 0xED, 0x71 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("out0", "(*),a", 3, new byte[] { 0xED, 0x39 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("out0", "(*),b", 3, new byte[] { 0xED, 0x01 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("out0", "(*),c", 3, new byte[] { 0xED, 0x09 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("out0", "(*),d", 3, new byte[] { 0xED, 0x11 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("out0", "(*),e", 3, new byte[] { 0xED, 0x19 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("out0", "(*),h", 3, new byte[] { 0xED, 0x21 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("out0", "(*),l", 3, new byte[] { 0xED, 0x29 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("outd", "\"\"", 2, new byte[] { 0xED, 0xAB }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("outi", "\"\"", 2, new byte[] { 0xED, 0xA3 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("pop", "af", 1, new byte[] { 0xF1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("pop", "bc", 1, new byte[] { 0xC1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("pop", "de", 1, new byte[] { 0xD1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("pop", "hl", 1, new byte[] { 0xE1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("pop", "ix", 2, new byte[] { 0xDD, 0xE1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("pop", "iy", 2, new byte[] { 0xFD, 0xE1 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("push", "af", 1, new byte[] { 0xF5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("push", "bc", 1, new byte[] { 0xC5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("push", "de", 1, new byte[] { 0xD5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("push", "hl", 1, new byte[] { 0xE5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("push", "ix", 2, new byte[] { 0xDD, 0xE5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("push", "iy", 2, new byte[] { 0xFD, 0xE5 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,(hl)", 2, new byte[] { 0xCB, 0x86 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZBit, 1, 0, 0x8600));
            AllInstructions.Add(new Instruction("res", "*,(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZBit, 1, 0, 0x8600));
            AllInstructions.Add(new Instruction("res", "*,a", 2, new byte[] { 0xCB, 0x87 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,b", 2, new byte[] { 0xCB, 0x80 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,c", 2, new byte[] { 0xCB, 0x81 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,d", 2, new byte[] { 0xCB, 0x82 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,e", 2, new byte[] { 0xCB, 0x83 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,h", 2, new byte[] { 0xCB, 0x84 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("res", "*,l", 2, new byte[] { 0xCB, 0x85 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "\"\"", 1, new byte[] { 0xC9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "c", 1, new byte[] { 0xD8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "m", 1, new byte[] { 0xF8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "nc", 1, new byte[] { 0xD0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "nz", 1, new byte[] { 0xC0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "p", 1, new byte[] { 0xF0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "pe", 1, new byte[] { 0xE8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "po", 1, new byte[] { 0xE0 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ret", "z", 1, new byte[] { 0xC8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("reti", "\"\"", 2, new byte[] { 0xED, 0x4D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("retn", "\"\"", 2, new byte[] { 0xED, 0x45 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "(hl)", 2, new byte[] { 0xCB, 0x16 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x1600));
            AllInstructions.Add(new Instruction("rl", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x1600));
            AllInstructions.Add(new Instruction("rl", "a", 2, new byte[] { 0xCB, 0x17 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "b", 2, new byte[] { 0xCB, 0x10 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "c", 2, new byte[] { 0xCB, 0x11 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "d", 2, new byte[] { 0xCB, 0x12 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "e", 2, new byte[] { 0xCB, 0x13 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "h", 2, new byte[] { 0xCB, 0x14 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rl", "l", 2, new byte[] { 0xCB, 0x15 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rla", "\"\"", 1, new byte[] { 0x17 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "(hl)", 2, new byte[] { 0xCB, 0x06 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0600));
            AllInstructions.Add(new Instruction("rlc", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0600));
            AllInstructions.Add(new Instruction("rlc", "a", 2, new byte[] { 0xCB, 0x07 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "b", 2, new byte[] { 0xCB, 0x00 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "c", 2, new byte[] { 0xCB, 0x01 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "d", 2, new byte[] { 0xCB, 0x02 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "e", 2, new byte[] { 0xCB, 0x03 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "h", 2, new byte[] { 0xCB, 0x04 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlc", "l", 2, new byte[] { 0xCB, 0x05 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rlca", "\"\"", 1, new byte[] { 0x07 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rld", "\"\"", 2, new byte[] { 0xED, 0x6F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "(hl)", 2, new byte[] { 0xCB, 0x1E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x1E00));
            AllInstructions.Add(new Instruction("rr", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x1E00));
            AllInstructions.Add(new Instruction("rr", "a", 2, new byte[] { 0xCB, 0x1F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "b", 2, new byte[] { 0xCB, 0x18 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "c", 2, new byte[] { 0xCB, 0x19 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "d", 2, new byte[] { 0xCB, 0x1A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "e", 2, new byte[] { 0xCB, 0x1B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "h", 2, new byte[] { 0xCB, 0x1C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rr", "l", 2, new byte[] { 0xCB, 0x1D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rra", "\"\"", 1, new byte[] { 0x1F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "(hl)", 2, new byte[] { 0xCB, 0x0E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0E00));
            AllInstructions.Add(new Instruction("rrc", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0E00));
            AllInstructions.Add(new Instruction("rrc", "a", 2, new byte[] { 0xCB, 0x0F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "b", 2, new byte[] { 0xCB, 0x08 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "c", 2, new byte[] { 0xCB, 0x09 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "d", 2, new byte[] { 0xCB, 0x0A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "e", 2, new byte[] { 0xCB, 0x0B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "h", 2, new byte[] { 0xCB, 0x0C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrc", "l", 2, new byte[] { 0xCB, 0x0D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrca", "\"\"", 1, new byte[] { 0x0F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rrd", "\"\"", 2, new byte[] { 0xED, 0x67 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("rst", "*", 1, new byte[] { 0xC7 }, Instruction.InstructionRule.RST, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,(hl)", 1, new byte[] { 0x9E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,(ix*)", 3, new byte[] { 0xDD, 0x9E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,(iy*)", 3, new byte[] { 0xFD, 0x9E }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,a", 1, new byte[] { 0x9F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,b", 1, new byte[] { 0x98 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,c", 1, new byte[] { 0x99 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,d", 1, new byte[] { 0x9A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,e", 1, new byte[] { 0x9B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,h", 1, new byte[] { 0x9C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,l", 1, new byte[] { 0x9D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "hl,bc", 2, new byte[] { 0xED, 0x42 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "hl,de", 2, new byte[] { 0xED, 0x52 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "hl,hl", 2, new byte[] { 0xED, 0x62 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "hl,sp", 2, new byte[] { 0xED, 0x72 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,ixh", 2, new byte[] { 0xDD, 0x9C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,ixl", 2, new byte[] { 0xDD, 0x9D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,iyh", 2, new byte[] { 0xFD, 0x9C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,iyl", 2, new byte[] { 0xFD, 0x9D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sbc", "a,*", 2, new byte[] { 0xDE }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("scf", "\"\"", 1, new byte[] { 0x37 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,(hl)", 2, new byte[] { 0xCB, 0xC6 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZBit, 1, 0, 0xC600));
            AllInstructions.Add(new Instruction("set", "*,(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZBit, 1, 0, 0xC600));
            AllInstructions.Add(new Instruction("set", "*,a", 2, new byte[] { 0xCB, 0xC7 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,b", 2, new byte[] { 0xCB, 0xC0 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,c", 2, new byte[] { 0xCB, 0xC1 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,d", 2, new byte[] { 0xCB, 0xC2 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,e", 2, new byte[] { 0xCB, 0xC3 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,h", 2, new byte[] { 0xCB, 0xC4 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("set", "*,l", 2, new byte[] { 0xCB, 0xC5 }, Instruction.InstructionRule.ZBit, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "(hl)", 2, new byte[] { 0xCB, 0x26 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x2600));
            AllInstructions.Add(new Instruction("sla", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x2600));
            AllInstructions.Add(new Instruction("sla", "a", 2, new byte[] { 0xCB, 0x27 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "b", 2, new byte[] { 0xCB, 0x20 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "c", 2, new byte[] { 0xCB, 0x21 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "d", 2, new byte[] { 0xCB, 0x22 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "e", 2, new byte[] { 0xCB, 0x23 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "h", 2, new byte[] { 0xCB, 0x24 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sla", "l", 2, new byte[] { 0xCB, 0x25 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "(hl)", 2, new byte[] { 0xCB, 0x36 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3600));
            AllInstructions.Add(new Instruction("sll", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3600));
            AllInstructions.Add(new Instruction("sll", "a", 2, new byte[] { 0xCB, 0x37 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "b", 2, new byte[] { 0xCB, 0x30 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "c", 2, new byte[] { 0xCB, 0x31 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "d", 2, new byte[] { 0xCB, 0x32 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "e", 2, new byte[] { 0xCB, 0x33 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "h", 2, new byte[] { 0xCB, 0x34 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sll", "l", 2, new byte[] { 0xCB, 0x35 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "(hl)", 2, new byte[] { 0xCB, 0x36 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3600));
            AllInstructions.Add(new Instruction("sl1", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3600));
            AllInstructions.Add(new Instruction("sl1", "a", 2, new byte[] { 0xCB, 0x37 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "b", 2, new byte[] { 0xCB, 0x30 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "c", 2, new byte[] { 0xCB, 0x31 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "d", 2, new byte[] { 0xCB, 0x32 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "e", 2, new byte[] { 0xCB, 0x33 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "h", 2, new byte[] { 0xCB, 0x34 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sl1", "l", 2, new byte[] { 0xCB, 0x35 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "(hl)", 2, new byte[] { 0xCB, 0x36 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3600));
            AllInstructions.Add(new Instruction("slia", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3600));
            AllInstructions.Add(new Instruction("slia", "a", 2, new byte[] { 0xCB, 0x37 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "b", 2, new byte[] { 0xCB, 0x30 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "c", 2, new byte[] { 0xCB, 0x31 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "d", 2, new byte[] { 0xCB, 0x32 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "e", 2, new byte[] { 0xCB, 0x33 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "h", 2, new byte[] { 0xCB, 0x34 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slia", "l", 2, new byte[] { 0xCB, 0x35 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("slp", "\"\"", 2, new byte[] { 0xED, 0x76 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "(hl)", 2, new byte[] { 0xCB, 0x2E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x2E00));
            AllInstructions.Add(new Instruction("sra", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x2E00));
            AllInstructions.Add(new Instruction("sra", "a", 2, new byte[] { 0xCB, 0x2F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "b", 2, new byte[] { 0xCB, 0x28 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "c", 2, new byte[] { 0xCB, 0x29 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "d", 2, new byte[] { 0xCB, 0x2A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "e", 2, new byte[] { 0xCB, 0x2B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "h", 2, new byte[] { 0xCB, 0x2C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sra", "l", 2, new byte[] { 0xCB, 0x2D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "(hl)", 2, new byte[] { 0xCB, 0x3E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "(ix*)", 4, new byte[] { 0xDD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3E00));
            AllInstructions.Add(new Instruction("srl", "(iy*)", 4, new byte[] { 0xFD, 0xCB }, Instruction.InstructionRule.ZIdX, 1, 0, 0x3E00));
            AllInstructions.Add(new Instruction("srl", "a", 2, new byte[] { 0xCB, 0x3F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "b", 2, new byte[] { 0xCB, 0x38 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "c", 2, new byte[] { 0xCB, 0x39 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "d", 2, new byte[] { 0xCB, 0x3A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "e", 2, new byte[] { 0xCB, 0x3B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "h", 2, new byte[] { 0xCB, 0x3C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("srl", "l", 2, new byte[] { 0xCB, 0x3D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "(hl)", 1, new byte[] { 0x96 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "(ix*)", 3, new byte[] { 0xDD, 0x96 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "(iy*)", 3, new byte[] { 0xFD, 0x96 }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "a", 1, new byte[] { 0x97 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "b", 1, new byte[] { 0x90 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "c", 1, new byte[] { 0x91 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "d", 1, new byte[] { 0x92 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "e", 1, new byte[] { 0x93 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "h", 1, new byte[] { 0x94 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "l", 1, new byte[] { 0x95 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "a,ixh", 2, new byte[] { 0xDD, 0x94 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "a,ixl", 2, new byte[] { 0xDD, 0x95 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "a,iyh", 2, new byte[] { 0xFD, 0x94 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "a,iyl", 2, new byte[] { 0xFD, 0x95 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("sub", "*", 2, new byte[] { 0xD6 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "a", 2, new byte[] { 0xED, 0x3C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "b", 2, new byte[] { 0xED, 0x04 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "c", 2, new byte[] { 0xED, 0x0C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "d", 2, new byte[] { 0xED, 0x14 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "e", 2, new byte[] { 0xED, 0x1C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "h", 2, new byte[] { 0xED, 0x24 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "l", 2, new byte[] { 0xED, 0x2C }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "(hl)", 2, new byte[] { 0xED, 0x34 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tst", "*", 3, new byte[] { 0xED, 0x64 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("tstio", "*", 3, new byte[] { 0xED, 0x74 }, Instruction.InstructionRule.NoTouch, 2, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "(hl)", 1, new byte[] { 0xAE }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "(ix*)", 3, new byte[] { 0xDD, 0xAE }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "(iy*)", 3, new byte[] { 0xFD, 0xAE }, Instruction.InstructionRule.ZIdX, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "a", 1, new byte[] { 0xAF }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "b", 1, new byte[] { 0xA8 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "c", 1, new byte[] { 0xA9 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "d", 1, new byte[] { 0xAA }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "e", 1, new byte[] { 0xAB }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "h", 1, new byte[] { 0xAC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "l", 1, new byte[] { 0xAD }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "ixh", 2, new byte[] { 0xDD, 0xAC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "ixl", 2, new byte[] { 0xDD, 0xAD }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "iyh", 2, new byte[] { 0xFD, 0xAC }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "iyl", 2, new byte[] { 0xFD, 0xAD }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("xor", "*", 2, new byte[] { 0xEE }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "ixh", 2, new byte[] { 0xDD, 0x24 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "ixh", 2, new byte[] { 0xDD, 0x25 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "iyh", 2, new byte[] { 0xFD, 0x24 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "iyh", 2, new byte[] { 0xFD, 0x25 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "ixl", 2, new byte[] { 0xDD, 0x2C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "ixl", 2, new byte[] { 0xDD, 0x2D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("inc", "iyl", 2, new byte[] { 0xFD, 0x2C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("dec", "iyl", 2, new byte[] { 0xFD, 0x2D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,b", 2, new byte[] { 0xDD, 0x60 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,c", 2, new byte[] { 0xDD, 0x61 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,d", 2, new byte[] { 0xDD, 0x62 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,e", 2, new byte[] { 0xDD, 0x63 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,ixh", 2, new byte[] { 0xDD, 0x64 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,ixl", 2, new byte[] { 0xDD, 0x65 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,a", 2, new byte[] { 0xDD, 0x67 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,b", 2, new byte[] { 0xDD, 0x68 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,c", 2, new byte[] { 0xDD, 0x69 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,d", 2, new byte[] { 0xDD, 0x6A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,e", 2, new byte[] { 0xDD, 0x6B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,ixh", 2, new byte[] { 0xDD, 0x6C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,ixl", 2, new byte[] { 0xDD, 0x6D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,a", 2, new byte[] { 0xDD, 0x6F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,b", 2, new byte[] { 0xFD, 0x60 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,c", 2, new byte[] { 0xFD, 0x61 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,d", 2, new byte[] { 0xFD, 0x62 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,e", 2, new byte[] { 0xFD, 0x63 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,ixh", 2, new byte[] { 0xFD, 0x64 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,ixl", 2, new byte[] { 0xFD, 0x65 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,a", 2, new byte[] { 0xFD, 0x67 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,b", 2, new byte[] { 0xFD, 0x68 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,c", 2, new byte[] { 0xFD, 0x69 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,d", 2, new byte[] { 0xFD, 0x6A }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,e", 2, new byte[] { 0xFD, 0x6B }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,ixh", 2, new byte[] { 0xFD, 0x6C }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,ixl", 2, new byte[] { 0xFD, 0x6D }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,a", 2, new byte[] { 0xFD, 0x6F }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixh,*", 3, new byte[] { 0xDD, 0x26 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyh,*", 3, new byte[] { 0xFD, 0x26 }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "ixl,*", 3, new byte[] { 0xDD, 0x2E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
            AllInstructions.Add(new Instruction("ld", "iyl,*", 3, new byte[] { 0xFD, 0x2E }, Instruction.InstructionRule.NoTouch, 1, 0, 0x0000));
        }
    }
}
