//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;link rel=&quot;Stylesheet&quot; href=&quot;style.css&quot; /&gt;
        ///        &lt;title&gt;Brass Z80 Assembler - Manual&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body id=&quot;manual&quot;&gt;
        ///        &lt;div id=&quot;page&quot;&gt;
        ///        &lt;div id=&quot;banner&quot;&gt;
        ///            &lt;img src=&quot;pig.png&quot; width=&quot;48&quot; height=&quot;48&quot; title=&quot;Oink&quot; /&gt;
        ///            &lt;h1&gt;Brass Manual&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///        
        ///        &lt;div id=&quot;menubar&quot;&gt;
        ///            &lt;ul id=&quot;nav&quot;&gt;
        ///                &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Getting Started&lt;/a&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap pig {
            get {
                object obj = ResourceManager.GetObject("pig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Main text properties */
        ///
        ///body, p, table, td, th, input, select, textarea, li {
        ///  	font-family: tahoma, verdana, arial;
        ///  	font-size: 11px;
        ///  	color: #333333;
        ///}
        ///
        ///body {
        ///  	background-color: #DDDDDD;
        ///}
        ///
        ///a {
        ///  	text-decoration: none;
        ///  	color: #000099;
        ///}
        ///a:hover {
        ///  	text-decoration: underline;
        ///  	color: #0000FF;
        ///}
        ///
        ///h1 {
        ///  	font-size: 22px;
        ///}
        ///h2 {
        ///  	font-size: 18px;
        ///}
        ///h3 {
        ///  	font-size: 14px;
        ///}
        ///h1, h2, h3, h4 {
        ///  	font-family: trebuchet ms, verdana, tahoma, arial, sans-serif; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
